version: '3.8'

# Define a custom network for all services to communicate internally
networks:
  internal:
    driver: bridge

services:

  # --- CONSOLIDATED DATABASE SERVICE ---
  unified-db: # Renamed to reflect single use
    image: postgres:latest
    container_name: unified-db
    ports:
      # Expose port 5000 for local development/tools, mapped to container's 5432
      - "5000:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unified_db # Changed DB name for clarity
    volumes:
      # Using a single volume for all data
      - unified_db_data:/var/lib/postgresql/data
    networks:
      - internal

  # --- Message Broker Service ---
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    networks:
      - internal

  # --- Application Services ---

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "4005:4005"
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      # *** UPDATED to point to UNIFIED-DB ***
      SPRING_DATASOURCE_URL: jdbc:postgresql://unified-db:5432/unified_db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_DATASOURCE_INITIALIZE: true
      SPRING_SQL_INIT_PLATFORM: postgres
      JWT_SECRET: THIS_IS_A_VERY_LONG_AND_SECURE_SECRET_KEY_FOR_JWT_32_BYTES
    depends_on:
      - unified-db # Dependency updated
    networks:
      - internal

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      # *** UPDATED to point to UNIFIED-DB ***
      SPRING_DATASOURCE_URL: jdbc:postgresql://unified-db:5432/unified_db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_DATASOURCE_INITIALIZE: true
      SPRING_SQL_INIT_PLATFORM: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    depends_on:
      - unified-db # Dependency updated
      - kafka
      - billing-service
    networks:
      - internal

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - internal

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    depends_on:
      - auth-service
      - patient-service
    networks:
      - internal

# Define persistent volumes for the databases
volumes:
  unified_db_data: # Only one volume needed now