server:
  port: 4004

auth:
  service:
    url: http://auth-service:4005

spring:
  cloud:
    gateway:
      routes:

        ### 1. AUTH SERVICE - PUBLIC ENDPOINTS (No JWT Validation)
        - id: auth-public-route
          uri: http://auth-service:4005
          predicates:
            # Signup and LogIn must be public
            - Path=/auth/signup,/auth/login
          filters:
            # Strip /auth off the URL before sending to the microservice
            - StripPrefix=1

        ### 2. AUTH SERVICE - PROTECTED ENDPOINTS (JWT Validation Applied)
        # This route comes immediately after the public one. It catches everything else
        - id: auth-protected-route
          uri: http://auth-service:4005
          predicates:
            # Catch all remaining paths under /auth/
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - JwtValidation # All other /auth/ paths are intercepted and validated

        ### 3. Patient Service - other endpoints (JWT protected)
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ### 4. API Docs - Patient
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        ### 5. API Docs - Auth
        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs